posts/urls.py
from django.urls import path
from . import views

app_name = 'posts'

urlpatterns = [
    path('', views.post_list, name="list"),
    path('new/post', views.posts_new, name="new_post"),
    path('<slug:slug>', views.post_page, name="page"),
]

sandbox/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.homepage),
    path('about/', views.about),
    path('posts/', include('posts.urls')),
    path('users/', include('users.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path
from . import views

app_name = 'users'

urlpatterns = [
    path('register/', views.user_register, name="user_register"),
    path('login/', views.login_view, name="login"),
    path('logout/', views.logout_view, name="logout"),
]

posts/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class Post(models.Model):
    title = models.CharField(max_length=200)
    body = models.TextField()
    slug = models.SlugField(max_length=200)
    date = models.DateTimeField(auto_now_add=True)
    banner = models.ImageField(default='fallback.png', blank=True)
    User = models.ForeignKey(User, on_delete=models.CASCADE, default=None)


    def __str__(self):
        return self.title

users/models.py
from django.db import models

# Create your models here.

posts/forms.py
from django import forms
from . import models

class CreatePost(forms.ModelForm):
    class Meta:
        model = models.Post
        fields = ['title', 'body', 'slug', 'banner']

posts/views.py
from django.shortcuts import render, redirect
from .models import Post
from django.contrib.auth.decorators import login_required
from . import forms

# Create your views here.
def post_list(request):
    posts = Post.objects.all().order_by('-date')
    return render(request, 'posts/posts_list.html', {'posts': posts})

def post_page(request, slug):
    post = Post.objects.get(slug=slug)
    return render(request, 'posts/post_page.html', {'post': post})

@login_required(login_url='/users/login/')
def posts_new(request):
    if request.method == 'POST':
        form = forms.CreatePost(request.POST, request.FILES)
        if form.is_valid():
            newpost = form.save(commit=False)
            newpost.User = request.user
            newpost.save()
            return redirect('posts:list')
    else:
        form = forms.CreatePost()
    return render(request, 'posts/posts_new.html', {'form': form})

sandbox/views.py
# from django.http import HttpResponse
from django.shortcuts import render

def homepage(request):
    # return HttpResponse("Hello World")
    return render(request, 'home.html')

def about(request):
    # return HttpResponse("About")
    return render(request, 'about.html')

users/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth import login, logout

# Create your views here.

def user_register(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            login(request, form.save())
            return redirect('posts:list')
    else:
        form = UserCreationForm()
    return render(request, 'users/register.html', {'form': form})

def login_view(request):
    if request.method == 'POST':
        form = AuthenticationForm(data=request.POST)
        if form.is_valid():
            login(request, form.get_user())
            if 'next' in request.POST:
                return redirect(request.POST.get('next'))
            else:
                return redirect('posts:list')
    else:
        form = AuthenticationForm()
    return render(request, 'users/login.html', {'form': form})

def logout_view(request):
    if request.method == 'POST':
        logout(request)
        return redirect('posts:list')

posts/templates/posts/post_page.html
{% extends 'layout.html' %}

{% block title %}
    {{ post.title }}
{% endblock %}

{% block content %}
    <section>
        <img src="{{ post.banner.url }}" alt="{{ post.title }}" class="banner">
        <h1>{{ post.title }}</h1>
        <p>{{ post.date }}</p>
        <p>{{ post.body }}</p>
    </section>
{% endblock %}

posts/templates/posts/posts_list.html
{% extends 'layout.html' %}
	
{% block title %}
	POST
{% endblock %}

{% block content %}
    <section>
        <h1>POST</h1>
    </section>

    {% for post in posts %}
    	<article>
            <h2>
                <a href="{% url 'posts:page' slug=post.slug %}">
                    {{ post.title }}
                </a>
            </h2>
            <p>{{ post.date }} by {{ post.User }}</p>
            <p>{{ post.body }}</p>
        </article>
    {% endfor %}

{% endblock %}

posts/templates/posts/posts_new.html
{% extends 'layout.html' %}

{% block title %}
    New Post
{% endblock %}

{% block content %}
    <section>
        <h1>New Post</h1>

        <form class="form-with-validation" action="{% url 'posts:new_post' %}" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form }}
            <button class="form-submit">Add Post</button>
        </form>
    </section>
{% endblock %}

templates/about.html
{% extends 'layout.html' %}
	
{% block title %}
	ABOUT
{% endblock %}

{% block content %}
    <h1>ABOUT</h1>
    <p>Chech out my <a href="/">ABOUT</a> page.</p>
{% endblock %}

templates/home.html
{% extends 'layout.html' %}
	
{% block title %}
	HOME
{% endblock %}

{% block content %}
    <h1>HOME</h1>
    <p>Chech out my <a href="/">HOME</a> page.</p>
{% endblock %}

templates/layout.html
<!doctype html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>
        {% block title %}
            Django App
        {% endblock %}
    </title>
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <script src="{% static 'js/main.js' %}"></script>
</head>
<body>
    <nav>
        <a href="/"><span role="img" aria-label="Home">🏠</span></a> |
        <a href="/about"><span role="img" aria-label="About">🆎</span></a> |
        <a href="{% url 'posts:list' %}"><span role="img" aria-label="Post">📰</span></a> |

        {% if user.is_authenticated %}
            <a href="{% url 'posts:new_post' %}"><span role="img" aria-label="New Post" title="New Post">🆕</span></a> |
            <form class="logout" action="{% url 'users:logout' %}" method="post">
                {% csrf_token %}
                <button class="logout-button" aria-label="User Logout" title="User Logout">👋</button>
            </form>
        {% else %}
            <a href="{% url 'users:user_register' %}"><span role="img" aria-label="Form">🚀</span></a> |
            <a href="{% url 'users:login' %}"><span role="img" aria-label="User Login" title="User Login">🔐</span></a>
        {% endif %}
    </nav>

    <main>
        {% block content %}

        {% endblock %}
    </main>


</body>
</html>

users/templates/users/login.html
{% extends 'layout.html' %}

{% block title %}
    User Login
{% endblock %}

{% block content %}
    <h1>User Login</h1>
    <form class="form-with-validation" action="/users/login/" method="post">
        {% csrf_token %}
        {{ form }}
        {% if request.GET.next %}
        	<input type="hidden" name="next" value="{{ request.GET.next }}">
        {% endif %}
        <button class="form-submit">Submit</button>
    </form>
{% endblock %}

users/templates/users/register.html
{% extends 'layout.html' %}

{% block title %}
    Register a User
{% endblock %}

{% block content %}
    <h1>Register new user</h1>
    <form class="form-with-validation" action="/users/register/" method="post">
        {% csrf_token %}
        {{ form }}
        <button class="form-submit">Submit</button>
    </form>
{% endblock %}